set(CMAKE_SYSTEM_NAME Windows)

set(PLATFORM_IS_WINDOWS TRUE CACHE BOOL "" FORCE)
set(PLATFORM_IS_LINUX FALSE CACHE BOOL "" FORCE)

# Stack size
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /STACK:16777216")

# Disable vcpkg applocal copy
set(X_VCPKG_APPLOCAL_DEPS_INSTALL OFF CACHE BOOL "")
